# Generated by Django 4.1.5 on 2023-02-06 16:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
                ('available', models.BooleanField(default=True)),
                ('rating', models.DecimalField(decimal_places=2, default=5, max_digits=3)),
                ('image', models.ImageField(default='products/default.png', upload_to='products/')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('bookmarked_by', models.ManyToManyField(blank=True, related_name='bookmarked_products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
